import turtle
turtle.pu()
turtle.setx(-75)
turtle.sety(75)
turtle.pd()
turtle.forward(50)
turtle.write("Lado A")
turtle.forward(50)
turtle.right(90)
turtle.forward(75)
turtle.write("Lado B")
turtle.forward(75)
turtle.right(90)
turtle.forward(100)          
turtle.right(90)
turtle.forward(150)
turtle.back(150)
turtle.right(180)
turtle.pu()
turtle.forward(75)
print("Ingrese los lados del Rectangulo")
a = input("Ingrese A ")
b = input("Ingrese B ")
print("Ingrese el color en ingles en el que se desea que se haga el Rectangulo")
print(" Marron: brown")
print(" Rojo: red")
print(" Verde: green")
print(" Negro: black")
print(" Amarillo: yellow")
print(" Azul: blue")
turtle.pencolor(input())
a=int(a)
b=int(b)
turtle.left(90)
turtle.pd()
turtle.forward(a/2)
turtle.write("Lado A",None,font=("Arial",5,"normal"))
turtle.forward(a/2)
turtle.write("Tu Rectangulo",None,font=("Arial",5,"normal"))
turtle.right(90)
turtle.forward(b/2)
turtle.write("Lado B",None,font=("Arial",5,"normal"))
turtle.forward(b/2)
turtle.right(90)
turtle.forward(a)             
turtle.right(90)
turtle.forward(b)


             



